export default {
  create: 'create',
  createText: '创建了任务',
  done: 'done',
  doneText: '完成了任务',
  reopen: 'reopen',
  reopenText: '重新打开了任务',
  update: 'update',
  updateText: '更新了任务',
  assign: 'assign',
  assignText: '把任务指派给&nbsp;&nbsp;{assignee}',
  unassign: 'unassign',
  unassignText: '取消了&nbsp;&nbsp;{assignee}&nbsp;&nbsp;的任务  ',
  deadline: 'deadline',
  deadlineText: '将任务截止日期设置为',
  noDeadline: 'noDeadline',
  noDeadlineText: '取消了任务截止日期',
  level: 'level',
  levelText: '将任务设置为&nbsp;&nbsp;{level}',
  addTag: 'addTag',
  addTagText: '添加了标签&nbsp;&nbsp;{tag}',
  removeTag: 'removeTag',
  removeTagText: '移除了标签&nbsp;&nbsp;{tag}'
}
